services:          #default synxtax
  databasefirst:        #naming convention for container
    build: /opt/employees-student-compose/dockercompose_st_emp-main/dockercompose_st_emp-main/student/Mysql/  #location of the docker file
    ports:     #port mapping my container to host port 
      - '3306:3306'  
    container_name: Database  #providing name to container
    network_mode:   #providing network mode
        bridge

  backendsecond: 
    build: /opt/employees-student-compose/dockercompose_st_emp-main/dockercompose_st_emp-main/student/backend/    
    ports:
      - '8080:8080'        
    container_name: Backend
    network_mode:
        bridge

  frontendthrid:
    build:  /opt/employees-student-compose/dockercompose_st_emp-main/dockercompose_st_emp-main/student/frontend/
    ports:
      - '80:80'
    container_name: Frontend
    network_mode:
        bridge

  employeedata:
    build:  /opt/employees-student-compose/dockercompose_st_emp-main/dockercompose_st_emp-main/Employee/psql-database/
    ports:
      - '5432:5432'
    container_name: database
    network_mode:
        bridge


  employeeback:
    build:  /opt/employees-student-compose/dockercompose_st_emp-main/dockercompose_st_emp-main/Employee/backend/
    ports:
      - '8081:8080'
    container_name: Back
    network_mode:
        bridge

  employeepsqldatabase:
    build:  /opt/employees-student-compose/dockercompose_st_emp-main/dockercompose_st_emp-main/Employee/frontend/
    ports:
      - '3000:3000'
    container_name: frontend
    network_mode:
        bridge
